### ISSUE TITLE
unable to build

### ISSUE THREAD

**Issue by The-Jat** [Meulengracht/vali-userspace#1]
This is the command line output which i am getting

mak@mak-VirtualBox:~/Downloads/mollen/App/vali-userspace$ cmake .
-- Install directory: /home/mak/Downloads/mollen/App/vali-userspace/install
-- GLM_INCLUDE_DIR = /home/mak/Downloads/mollen/App/vali-userspace/glm
-- Found GRLM in /home/mak/Downloads/mollen/App/vali-userspace/glm
-- Found GLFW3 in /usr/include
-- Using the builtin libz library sources
-- Using the builtin lzma library sources
-- Using the builtin bzip2 library sources
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find VIOARR (missing: VIOARR_LIBRARY)
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  SDL/cmake/FindVIOARR.cmake:50 (find_package_handle_standard_args)
  SDL/CMakeLists.txt:151 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/mak/Downloads/mollen/App/vali-userspace/CMakeFiles/CMakeOutput.log".

**Comment by Meulengracht** [comment]
Sorry that I've seen your message so late, I've answered your message on MollenOS github!
